### ISSUE TITLE
Where I can get raw Delicious dataset?

### ISSUE THREAD

**Issue by Abhinav43** [QData/LaMP#1]
Hi, I am trying to get raw delicious dataset but most of delicious dataset available on internet are in tf-idf format or feature vectors. 

How can I get raw data ( sentences , one hot encoded labels ( or simple labels )) ?

Usually when we have text data we do  

`raw_data -> clean data -> build vocab -> encode sentences -> embed sentences with word2vec -> feed
`

But if I have binary vectors how I can feed it to neural? should i feed it directly ?
If i want to use word2vec then how I can use on this dataset?

**Comment by jacklanchantin** [comment]
The delicious dataset doesn't provide sequence features. Only bag of words features. Its likely most of the inputs were not sentences. If you look at the paper proposing the delicious dataset, the authors note "It contains textual data of web pages along with their tags, and is used to train a multilabel classifier for automated tag suggestion." So this textual data is what they provide as features.
