### ISSUE TITLE
Cannot downloads dataset

### ISSUE THREAD

**Issue by chetankm1992** [QData/LaMP#10]
When running command `wget http://www.cs.virginia.edu/~jjl5sw/data/lamp_datasets.tar.gz`, it gives the error as shown in attached screenshot. Could you please guide me how I can download the dataset? Thanks in advance.

![image](https://user-images.githubusercontent.com/28491233/181824503-b6b0a96f-9ec8-4b70-86d2-116b30c4be87.png)

**Comment by jacklanchantin** [comment]
Sorry, should be fixed now

**Comment by jacklanchantin** [comment]
See the new link
