### ISSUE TITLE
Datasets used in the paper

### ISSUE THREAD

**Issue by JunwenBai** [QData/LaMP#4]
Hi, Jack,
I noticed that some of the datasets (like delicious) have integer features (index) and then you convert the words to vectors. It is quite different from the dataset from other sources. For example, the delicious dataset I downloaded from http://mulan.sourceforge.net/datasets-mlc.html has 500-d float features and 983-d labels. But in your dataset, the features are discrete integers and then converted to embeddings. How are they correlated? Thx!
Best

**Comment by jacklanchantin** [comment]
Hey, I just re-downloaded the delicious dataset from that link, and the arff files provided do not include float features for the inputs. Are you sure that's the one you are referencing?

**Comment by jacklanchantin** [comment]
I think I see what you were referencing with the 500-d features. Those are all possible 500 words. But we convert each of those to a d-dimensional an embedding (default 512). Does that make sense?

**Comment by JunwenBai** [comment]
Oh, I see. Thx for the explanation!
